# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace
    exclude: ^doc/_static/.*.svg

# Python linter (Flake8)
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8

# Python formatting
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

# Python black(en) for docs
- repo: https://github.com/asottile/blacken-docs
  rev: v1.10.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]

# Flake
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
  - id: flake8

# pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v2.10.0
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

# Jupyter notebook quality control.
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.5.9
  hooks:
  - id: nbqa-black
    additional_dependencies: [black==20.8b1]
  - id: nbqa-pyupgrade
    additional_dependencies: [pyupgrade==2.7.4]
