# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace
    exclude: ^doc/_static/.*.svg

# Python linter (Flake8)
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8

# Python formatting
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

# Python black(en) for docs
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]

# pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.1
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

# Sorted python imports
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]

# Typing
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.950
  hooks:
    - id: mypy
      exclude: ^docs/

# Jupyter notebook quality control
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
  - id: nbqa-flake8
    args: [--nbqa-mutate]
  - id: nbqa-black
    args: [--nbqa-mutate]
  - id: nbqa-pyupgrade
    args: [--nbqa-mutate]
# While I found out how to keep isort from overwriting the black changes,
# I can't manage to get this done for the nbqa versions.
# Thus, let's fo without nbqa-isort for now.
#  - id: nbqa-isort
#    args: [--nbqa-mutate]

# Exclude kept as a reminder for that being possible
- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout
      exclude: ^tests/data/databricks_notebook\.ipynb$
